from google import genai

client = genai.Client(api_key="Insert your API key here")

# Number of iterations
iterations = 100
kundetyper = [

    "Nystartet webshop-ejer",
    "Frisør med lokal salon",
    "Tømrer uden hjemmeside",
    "Psykolog med privat praksis",
    "Selvstændig konsulent",
    "Ejendomsmægler med boligsite",
    "Tandlæge der vil i gang med Google Ads",
    "Café-ejer der vil på Instagram",
    "Personlig træner med ny YouTube-kanal",
    "Fotograf der vil vise portfolio online",
    "Advokat med gammel hjemmeside",
    "Revisor med LinkedIn-profil",
    "Coach uden sociale medier",
    "Møbelsnedker med fysisk butik",
    "Restaurant der vil have flere bookinger",
    "Tatovør der vil vises på Google Maps",
    "Ejer af yoga-studie med ledige hold",
    "Mekaniker der vil findes på nettet",
    "Hundetræner med online kurser",
    "Lokal kunstner med galleri",
    "Blogger der vil tjene penge på trafik",
    "Influencer der vil optimere engagement",
    "Online boghandel med lav trafik",
    "Konsulentfirma med få leads",
    "Startup der skal bruge branding",
    "VVS'er der vil vises i lokale søgninger",
    "Grafisk designer der vil ses på Instagram",
    "Musiker der vil promovere nye sange",
    "Smykkedesigner med Etsy-shop",
    "Vinbutik der vil sende nyhedsbreve",
    "Hundefrisør med Facebook-side",
    "Ejendomsudvikler med projektsider",
    "Økologisk landmand med gårdsalg",
    "Livsstilscoach med webinarer",
    "Ejer af rideskole med sæsonhold",
    "Kursusudbyder med e-learning platform",
    "Kiropraktor der vil have flere bookinger",
    "Bryllupsplanlægger med ny portefølje",
    "Cateringfirma med weekendbookinger",
    "IT-konsulent med nicheydelser",
    "Børnetøjsbutik med Instagramshop",
    "Arkitekt med designportefølje",
    "Ejerskab af lokal vinbar",
    "Massageklinik uden online tilstedeværelse",
    "Forfatter der vil markedsføre en bog",
    "Gamingstreamer der vil tiltrække følgere",
    "Lille tøjbrand med Shopify-shop",
    "Webbureau der vil tiltrække flere leads",
    "Rejsebureau med nicheoplevelser",
    "Foredragsholder med events",
    "Modebutik der vil lave kampagner",
    "Elektriker der vil til tops på Google",
    "Planteskole med webshop",
    "Online kursusskole med lav konvertering",
    "Håndværker med forældet hjemmeside",
    "Vinimportør med abonnementsservice",
    "Fitnesscenter med ny app",
    "Dyreklinik med akutservice",
    "Malervirksomhed med flotte cases",
    "Fødevareproducent med ny produktserie",
    "Plakatbutik der vil vækste på Pinterest",
    "HR-konsulent med små og mellemstore kunder",
    "Rengøringsfirma med nye ydelser",
    "Bryggeri med ny ølserie",
    "Møbelforretning med showroom",
    "Biavler med lokal honning",
    "E-sports hold med sponsorbehov",
    "Autoforhandler med brugte biler",
    "Fotostudie med tilbudskampagner",
    "Psykoterapeut med venteliste",
    "Tegneserietegner med Patreon-side",
    "Festivalarrangør med billetshop",
    "Online coach med digitalt produkt",
    "Havearkitekt med mange billeder",
    "Boligstylist med før-efter billeder",
    "Sprøgsmå virksomhed der aldrig har lavet markedsføring",
    "IT-udvikler med SaaS-produkt",
    "Online magasin med bannerannoncer",
    "Datingcoach med nichepublikum",
    "Spiludvikler med nyt mobilspil",
    "Fagforening der vil nå unge",
    "Fødevarestartup med crowdfunding",
    "Tøjdesigner med kollektion på vej",
    "Selvlært SEO-specialist med spørgsmål",
    "Ejer af lille hotel uden bookingmotor",
    "Cykelværksted med mange anmeldelser",
    "Planteservice til virksomheder",
    "Dykkerinstruktør med sæsonkurser",
    "Lokal tv-station med streamingindhold",
    "Børnefotograf med kampagnetilbud",
    "Online sminkebutik med lav konvertering",
    "Kunsthåndværker med udstillinger",
    "Kursusplatform med brug for remarketing",
    "Mobilreparatør med travl butik",
    "Legetøjsbutik med nicheprodukter",
    "Lokal frisør med ny ejer",
    "Konditor med bryllupskager",
    "Online butik med brug for ny branding",
    "Byggemarked med dårlige anmeldelser",
    "Gulvmand med gode cases og ingen markedsføring",
    "Rideskole med camps og sommerhold",
    "Online psykolog med teleterapi",
    "Udlejer af ferielejligheder",
    "Musikskole med ledige pladser",
    "Hundepasser med tilfredse kunder",
    "Spritskriver der vil markedsføre sine bøger"
]

for kundetype in kundetyper:
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=f"Kunden skal være af typen {kundetype}. Jeg driver en online marketing virksomhed der hedder CJComplex. Jeg vil gerne have at du laver simulering af kundeservice responser til vores kunder. Det skal være en simulering af et spørgsmål fra en kunde efterfulgt af et svar fra en kundeservice medarbejder. Jeg vil gerne have dem i 1 liners, både spørgsmål og svar. Efter hvert svar skal der være en newline. Jeg vil gerne have at du generer 100 stks, alle med tilfældige spørgsmål inden for online marketing med gode kundeservice svar. Responsen du generer skal ikke indeholde andet end spørgsmål og svar. Ikke noget med formatering eller numering",
    )

    # Remove the first line from the response
    lines = response.text.splitlines()
    output = "\n".join(lines[1:])  # Skip the first line

    # Append the output to GoogleAIApi.txt
    with open("GoogleAIApi.txt", "a", encoding="utf-8") as file:
        file.write(output + "\n")
    print(f"Generated content for customer type: {kundetype}")
